#cloud-config

runcmd:
  - [ wget, "https://cloudron.io/cloudron-setup" ]
  - [ chmod, +x, cloudron-setup ]
  - './cloudron-setup --skip-reboot --data ''${replace(cloudronData, "\n", "")}'''

  #hack mail relay since it's not supported in Data (1.2.0+)
  - mysql -u root -ppassword -e "REPLACE INTO settings (name, value) VALUES (\"mail_relay\", '${replace(replace(mail_relay,"\"","\\\""),"\n","")}')" box

  # reboot
  - systemctl stop mysql
  - systemctl reboot

